Add a self loop to account for smiles that only have 1 atom
Examples include C, N, or O without explicit Hs. If these molecules end up at the end of the batch, it causes errors when pooling the atomic representations into molecular representations using `batch`. 

Example traceback is 
```
Traceback (most recent call last):
  File "/home/kspieker/code/chiral_gnn/train.py", line 43, in <module>
    train_loss, train_acc = train(model, train_loader, optimizer, loss, stdzer, args.device, scheduler, args.task)
  File "/home/kspieker/code/chiral_gnn/model/training.py", line 21, in train
    out = model(data)
  File "/home/kspieker/.conda/envs/chiral_gnn_py37/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/kspieker/code/chiral_gnn/model/gnn.py", line 105, in forward
    return self.ffn(self.pool(h, batch)).squeeze(-1)
  File "/home/kspieker/.conda/envs/chiral_gnn_py37/lib/python3.7/site-packages/torch_geometric/nn/glob/glob.py", line 28, in global_add_pool
    return scatter(x, batch, dim=0, dim_size=size, reduce='add')
  File "/home/kspieker/.conda/envs/chiral_gnn_py37/lib/python3.7/site-packages/torch_scatter/scatter.py", line 152, in scatter
    return scatter_sum(src, index, dim, out, dim_size)
  File "/home/kspieker/.conda/envs/chiral_gnn_py37/lib/python3.7/site-packages/torch_scatter/scatter.py", line 11, in scatter_sum
    index = broadcast(index, src, dim)
  File "/home/kspieker/.conda/envs/chiral_gnn_py37/lib/python3.7/site-packages/torch_scatter/utils.py", line 12, in broadcast
    src = src.expand(other.size())
RuntimeError: The expanded size of the tensor (172) must match the existing size (173) at non-singleton dimension 0.  Target sizes: [172, 300].  Tensor sizes: [173, 1]
```